name: Run Tests
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.4.2"]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install --only=test --no-root

      - name: Run pytest
        run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
